### ISSUE TITLE
Looking for an optional feature to support more than one role

### ISSUE THREAD

**Issue by shandonjuan** [aws-azure-login/aws-azure-login#1]
This works great but does not satisfy the condition when a user has more than one role. I have been trying to figure out a way to adapt this by prompting the user to select a role but I am having issues due to the asynchronous nature of the script. 

For example, my roles array actually has these roles:
0 '144343243434:role/SSO_ReadOnlyUser'
1 '842741343440:role/SSO_SB1_GlobalAdmin'
2 '263434343266:role/SSO-DT1-ReadOnly'

I would like to request such a feature be added or if you could point me in the right direction on where the script needs to be modified. Thanks!

**Comment by dtjohnson** [comment]
Multiple profiles are supported in the usual AWS CLI way with the --profile flag. From the docs:

```
$ aws configure --profile foo
$ aws-azure-login --configure --profile foo
```

**Comment by shandonjuan** [comment]
Hey DT - Thanks for the prompt response!


Azure AD supports custom role assignment for AWS, so now a SAML token can have multiple roles listed in the attribute statement.  Here is an example of what the role claim looks like when custom roles are used and multiple roles are assigned to a user:

               <Attribute Name="https://aws.amazon.com/SAML/Attributes/Role">
    <AttributeValue>arn:aws:iam::295478307378:role/SSO_ReadOnlyUser,arn:aws:iam::295478307378:saml-provider/WAAD</AttributeValue>
    <AttributeValue>arn:aws:iam::143074478378:role/SSO_CwReadOnly,arn:aws:iam::143074478378:saml-provider/WAAD</AttributeValue>
</Attribute>

In the login.js script, you extract the role claim value with the following line:

const roleAndPrincipal = saml("Attribute[Name='https://aws.amazon.com/SAML/Attributes/Role']").text();

However, when multiple roles are defined, the string being returned is 'arn:aws:iam::295478307378:role/SSO_ReadOnlyUser,arn:aws:iam::295478307378:saml-provider/WAADarn:aws:iam::143074478378:role/SSO_CwReadOnly,arn:aws:iam::143074478378:saml-provider/WAAD', so when the string is split, it ends up as:

                roleArn = arn:aws:iam::295478307378:role/SSO_ReadOnlyUser
principalArn =  arn:aws:iam::295478307378:saml-provider/WAADarn:aws:iam::143074478378:role/SSO_CwReadOnly

This results in only the first role ARN being available to the user, and the principal ARN being incorrect.  Playing around with the code, we can pull the individual roles out into an array by replacing the above code with something along the lines of:  (pardon the grammar, I'm not familiar with jscript)

                var roles = [];
                saml("Attribute[Name='https://aws.amazon.com/SAML/Attributes/Role']").children().each(function(i, xmlItem){
                                roles.push(xmlItem.childNodes[0].data);
                });


Our problem is that we have no idea how to stop the script execution, prompt the user, and wait for the user to select a role, before continuing on. Any help would be greatly appreciated.  We are very thankful for your work on this, we were almost dead in the water before finding your work.  Here is our work in progress:

                var roles = [];
                console.log("Select a Role:");
                saml("Attribute[Name='https://aws.amazon.com/SAML/Attributes/Role']").children().each(function(i, xmlItem){
                                roles.push(xmlItem.childNodes[0].data);
                                console.log(i, xmlItem.childNodes[0].data.split(",")[0].split("::")[1]);
                });

                var roleSelection
                if(roles.length > 1){
                                inquirer.prompt([{
                                                name: "roleSelection",
                                                message: "Selection:"
                                }])
                }else{
                                roleSelection = 0
                }

                const roleAndPrincipal = roles[roleSelection];

**Comment by dtjohnson** [comment]
Got it. It's an easy fix. I just published v0.2.0 with support for multiple role attributes. Give it a whirl and let me know if it works for you.

**Comment by shandonjuan** [comment]
This will work! only thing is the arrow keys are not working to change roles. Is there another mechanism I can try?

**Comment by dtjohnson** [comment]
That's odd. You tried the up and down arrow keys? It's just using the standard [inquirer list](https://www.npmjs.com/package/inquirer#list---type-list) prompt. There is a [raw list](https://www.npmjs.com/package/inquirer#raw-list---type-rawlist) prompt type that uses numeric input for the choice...

**Comment by shandonjuan** [comment]
I figured it out. It seems to be an issue with Gitbash on windows. When I use the standard windows command prompt, it works just fine!

This is a tremendous help. you have no idea! thank you again!

**Comment by dtjohnson** [comment]
Awesome. Glad it works!
