### ISSUE TITLE
cannot run the aws-azure-login commands

### ISSUE THREAD

**Issue by Raghuveer123** [aws-azure-login/aws-azure-login#101]
I'm able to install aws-azure-login but cannot run this command. please see the issues below.

PS C:\Users\> aws-azure-login --help aws-azure-login : The term 'aws-azure-login' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + aws-azure-login --help + ~~~~~~~~~~~~~~~ + CategoryInfo          : ObjectNotFound: (aws-azure-login:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException

**Comment by kennethaasan** [comment]
Hi @Raghuveer123, It sounds like an issue with your system or with windows. It works fine on my Mac: 
<img width="1259" alt="Screenshot 2019-11-11 at 17 49 16" src="https://user-images.githubusercontent.com/1437394/68605038-026ff880-04ac-11ea-8663-4d3d41d1e961.png">

**Comment by Raghuveer123** [comment]
Interesting,don't know where to troubleshoot?

**Comment by kennethaasan** [comment]
@Raghuveer123 I would try to google something like _windows npm global command not found_

**Comment by Raghuveer123** [comment]
@kennethaasan Now after uninstalling the node js and after installing the node js LTS version 12.13.0.I'm able to run cli commands.Does this aws-azure-login npm module works on latest version?

**Comment by kennethaasan** [comment]
Tested now and it works on Node.js version 12 and 13 on Mac.
