### ISSUE TITLE
aws-azure-login support with latest nodejs version

### ISSUE THREAD

**Issue by Raghuveer123** [aws-azure-login/aws-azure-login#102]
@kennethaasan Now after uninstalling the node js and installing the node js LTS version 12.13.0.I'm able to run cli commands.Does this aws-azure-login npm module works on latest version 13.1.0?

**Comment by kennethaasan** [comment]
I think it should. But I have not tested it. Sticking to LTS versions myself.

**Comment by Raghuveer123** [comment]
@kennethaasan Can you try with the latest version plz?

**Comment by kennethaasan** [comment]
Tested now and it works on Node.js version 12 and 13 on Mac.
