### ISSUE TITLE
ERROR: The process with PID xxxx(child process of PID yyyy) could not be terminated.

### ISSUE THREAD

**Issue by WParnell** [aws-azure-login/aws-azure-login#107]
Hi there,
When logging on with the gui mode I receive the following error message.  This can sometimes have multiple PID error lines.

>aws-azure-login --mode gui
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Please complete the login in the opened window
ERROR: The process with PID 18564 (child process of PID 21952) could not be terminated.
Reason: There is no running instance of the task.

When logging on with the cli version I get a similar error

>aws-azure-login
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
? Username: xxxxxx
? Password: [hidden]
We've sent a notification to your mobile device. Please open the Microsoft Authenticator app to respond.
ERROR: The process "28456" not found.

Has anyone come across this error before and if so, what would be causing it, and how can I fix it?
It does not stop the login process from completing and I can use the AWS CLI correctly after authentication.

Best Regards,
Bill

**Comment by kennethaasan** [comment]
Hey Bill,

I haven't seen this error before. Can you try to install the latest version that was released today to see if that makes a change?

**Comment by WParnell** [comment]
Hi there Kenneth,
The latest update *seems* to have resolved the error message I was receiving.
If it re-occurs I will open a new issue.
Many thanks
Bill
