### ISSUE TITLE
errors running npm install -g aws-azure-login on REHL

### ISSUE THREAD

**Issue by ghost** [aws-azure-login/aws-azure-login#11]
Hi
I am currently running the following on 

[ec2-user@ip-10-0-2-108 ~]$ aws --v
aws-cli/1.11.170 Python/2.7.5 Linux/3.10.0-693.el7.x86_64 botocore/1.7.28
[ec2-user@ip-10-0-2-108 ~]$ phantomjs -v
2.1.1
[ec2-user@ip-10-0-2-108 ~]$ node -v
v8.7.0
[ec2-user@ip-10-0-2-108 ~]$ npm -v
5.5.1
[ec2-user@ip-10-0-2-108 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)

Now, when I run 

Now, when I run 

[ec2-user@ip-10-0-2-108 ~]$ **sudo npm install -g aws-azure-login**
/usr/bin/aws-azure-login -> /usr/lib/node_modules/aws-azure-login/bin/index.js

> phantomjs-prebuilt@2.1.15 install /usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /bin/phantomjs
Looks like an `npm install -g`
Found PhantomJS at /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying
Writing location.js file
Error checking path, continuing { Error: EACCES: permission denied, open '/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/location.js'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at writeLocationFile (/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/util.js:84:6)
    at Promise._successFn (/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/install.js:366:11)
    at nextTickCallback (/usr/lib/node_modules/aws-azure-login/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/location.js' }
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1508039743191/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1508039743191/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1508039743191/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1508039743191/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-15T03_55_48_362Z-debug.log

**Comment by dtjohnson** [comment]
Try with sudo.

**Comment by ghost** [comment]
I have tried it with root same result
[root@ip-10-0-2-108 ec2-user]# npm install -g aws-azure-login> phantomjs-prebuilt@2.1.15 install /usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /bin/phantomjs
Looks like an `npm install -g`
Found PhantomJS at /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying
Writing location.js file
Error checking path, continuing { Error: EACCES: permission denied, open '/usr/lib/node_modules/aws-azure-login/node_modules/phantomjs-prebuilt/lib/location.js'

**Comment by dtjohnson** [comment]
Looks like there is a PhantomJS issue with this: https://github.com/Medium/phantomjs/issues/707

Seems all you need to do is install with the --unsafe-perm flag:
```
npm install -g aws-azure-login --unsafe-perm
```

**Comment by ghost** [comment]
Thanks this resolved the issue :)
