### ISSUE TITLE
Region and Output format on config and credential files

### ISSUE THREAD

**Issue by muthusk** [aws-azure-login/aws-azure-login#115]
Is there a way to save the region and output format in the profile. While configuring (aws-azure-login --configure )these should be collected?

**Comment by CodySchluenz** [comment]
You can't save them while running configure. It is mentioned in the readMe that if you want to save region, you have to manually open the ./aws/config file and save a region, i.e. add "region=us-east-1" to a specific profile.

**Comment by Jo-IE** [comment]
Hi, I am interested in the recent (entry level) web dev opening at Sportradar (Germany). Is there a good first issue that I can work on to learn more about the code base? Thank you in advance!
