### ISSUE TITLE
Unable to login when Azure AD is federated with on prem AD through ADFS

### ISSUE THREAD

**Issue by janejjshen** [aws-azure-login/aws-azure-login#12]
Hi there! I have a situation where the Azure AD is federated with an on-prem AD through ADFS and the login will fail. The error output is "We don't recognize this user ID or password" but the returned content page actually displays "We can't sign you in
Your browser is currently set to block cookies. You need to allow cookies to use this service." 

Normally PhantomJS should handle the cookies handling (I've even tried to enable cookies, enable JS, reset the user agent), so I am not sure where things went south. The difference here is, when doing a normal login flow in the browser, there's an extra level of redirect to "sts.xxxxx.com" for login credentials before we're redirected to the "apps" screen. 

Any help to get this working is appreciated :) Thanks!

**Update**: I modified the code to trigger the direction in phantomJS, and eventually reached a page that contains the SAML Assertion between the ADFS server and Azure. Examining the browser data it doesn't seem like the SAML assertion for AWS is available anywhere. I am suspecting that piece is handled between ADFS and Azure internally and not available for us.

**Comment by janejjshen** [comment]
Forked the solution and added handling of the redirection logic... Should be working now, exclusively with ADFS federated Azure ADs.

**Comment by dtjohnson** [comment]
Very nice. Did you want to submit that as a pull request?

**Comment by janejjshen** [comment]
I have the code only working with ADFS redirection, so will need to modify it to be more generic: If redirection is happening, handle it, or else don't bother. 

What's your take on whether we let the user set it in configuration ("Does the login screen take you to your corporation's login page?"), or read the page for "landmarks"(Look for html element based on known ID/name) and handle accordingly?

**Comment by dtjohnson** [comment]
Does Azure support redirections other than ADFS? I'm sure ADFS is a common use case so I'd prefer to auto-detect it without any additional configuration.

**Comment by rfarro** [comment]
I have been trying to get this to work the last couple of day. I keep getting the error below in bold. I have replaced anything that could be compromising. I've verified that the link provided in the "aws-azure-login Loading Azure login page" does work. 

 aws-azure-login Page opened +784ms
? Username: myusername
? Password: [hidden]
  aws-azure-login Populating and submitting login form +7s
**info: TypeError: undefined is not an object (evaluating 'document.forms[0].login
.value = username')
info:   undefined:2 in anonymous
info:   :6**
  aws-azure-login Waiting for page to load +31ms
  aws-azure-login Page loaded +0ms
Terminate batch job (Y/N)?

**Comment by janejjshen** [comment]
Looks like Microsoft has introduced a new login page. The page content has changed, and the username input field is now called "**loginfmt**". In addition, the password entry screen now requires a form submission. Seems like our tool needs updating...

**Comment by rfarro** [comment]
How would I go about fixing what is in place?

**Comment by ghost** [comment]
Any plans to release the version that works with AzureAD and ADFS redirection? I have the same issue

**Comment by dtjohnson** [comment]
Unfortunately, I don't have an ADFS setup to try myself. It should work if you run with the new `--gui` option. If you want/need to stay fully in the CLI, then someone needs to do the work and submit a PR. It should be easier with the new way the code is written.

**Comment by kennethaasan** [comment]
Old issue. Please re-open if this is still a problem for you with the latest version.
