### ISSUE TITLE
Not creating credentials in .aws/credentials file after login 

### ISSUE THREAD

**Issue by arikbidny** [aws-azure-login/aws-azure-login#121]
Hey, 
I succesfully Loginned with my azure account and choose a role - no error presented. 
But when i'm running aws s3 ls command im getting - Unable to locate credentials. You can configure credentials by running "aws configure".
My .aws/credentials file empy even after succesfull connection ,
Please help with this issue . 
thanks

**Comment by kennethaasan** [comment]
Did you run `aws-azure-login --configure`?

**Comment by arikbidny** [comment]
@kennethaasan  Sure, 
I did this procedure from Linux Server and it works fine , with Windows I have some issues.

**Comment by kennethaasan** [comment]
I see. I don't have access to Windows, so I'm not able to help you. I'll happily accept a PR that fixes Windows.

**Comment by larsschumachenko** [comment]
@arikbidny Do you use the dockerized version on windows?

If yes, verify that you enabled sharing the drive (Should be drive C) in the docker settings. (https://token2shell.com/howto/docker/sharing-windows-folders-with-containers/)
Restart docker after the setting change and try it again.

If that's already the case or you don't use the docker version I also have no idea what could be wrong.

**Comment by arikbidny** [comment]
@larsschumachenko thanks but I'm using windows 10 machine with without docker, 
I figured it out how to solve the issue: 
I'm running: aws-azure-login --mode gui --no-disable-extensions
and now it works fine , I also changed the Login.js code in order to work with eu-central-1 amazon sts service. 
Anyway thanks all for your responses .
