### ISSUE TITLE
How safe is using azure_default_remember_me=true ?

### ISSUE THREAD

**Issue by ohuk2** [aws-azure-login/aws-azure-login#124]
How exactly does that feature work and how are the credentials/session protected? The documentation says it caches the session cookie but I just tried after having been away from the CLI overnight, I would have thought my session cookies had expired by then but it still let me through without asking for the password or giving a MFA challenge...:

C02VD05KG8WN:.aws$ aws-azure-login --profile xxx
Logging in with profile 'xxx'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
? Role: arn:aws:iam::111111111111:role/devops
? Session Duration Hours (up to 12): 1
Assuming role arn:aws:iam::111111111111:role/devops

Looking at my cookies I see the below so they appear to be encrypted at least (is the key from keychain on the Mac?). Is it the ESTSAUTHPERSISTENT cookie that caches the session, I guess there is no caching of my user credentials anywhere?

`C02VD05KG8WN: $ sqlite3 ~/.aws/chromium/Default/Cookies
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> select * from cookies;
13227967625247301|login.microsoftonline.com|MSCC||/|13261663625247301|1|1|13227967625247301|1|1|1|v10E?xxxxxC8q?>|0
13227967613042883|.login.microsoftonline.com|brcap||/|13790275200000000|1|0|13227967613042883|1|1|1|v1xxxxxm*#F??6???|0
13227967630451249|login.microsoftonline.com|clrc||/|13230559630000000|0|0|13227967630451249|1|1|1|v10?xxxxx????|-1xxxxx?e?z&???|0499|.microsoftonline.com|wlidperf||/|13790275200000000|1|0|13227967624870499|1|1|1|v10?TS
13227967664057042|.login.microsoftonline.com|ESTSAUTHPERSISTENT||/|13235743664057042|1|1|13227967664057042|1|1|1|v10?²????u^?xxxxx?Q?|0
13227967664057325|login.microsoftonline.com|buid||/|13230559664057325|1|1|13227967664057325|1|1|1|v10\xxxxxxx??C???<]l|0
13227967664057243|.login.microsoftonline.com|ch||/|13235743664057243|1|0|13227967664057243|1|1|1|v10?0Ý??rxxxxxd/??y7':ʉ? @??+|0Uw|??7664057399|login.microsoftonline.com|fpc||/|13230559664057399|1|1|13227967664057399|1|1|1|v10????,?ISP??V??\xxxxxxx???]v|0
sqlite> `

**Comment by larsschumachenko** [comment]
@ohuk2 
Setting remember_me to true is doing the following:
- Chromium starts using a persistent profile directory (~/.aws/chromium)
- The functionality relies fully on the browser profile like any other browser you might use
- At the end of the login flow there is a dialog asking for "Stay signed in?". This question is answered with Yes.

I do not know which cookie is doing what, as this depends on the implementation from Microsoft and might change over time, however credentials are not stored anywhere.

**Comment by Archehandoro** [comment]
Setting remember_me to true always bypasses MFA. Ideally, remembering password and MFA should be different workflows. I don't want to type my password but I want to be asked for MFA.

**Comment by larsschumachenko** [comment]
@Archehandoro Such settings are controlled on Azure AD level. aws-login itself only interacts with the microsoft page. So if your Azure AD tenant is configured to regulary ask you for MFA, then it will be done. If not, then not. That behaviour is not controllable from client side.

**Comment by Archehandoro** [comment]
@larsschumachenko MFA is enabled in my tenant and when having remember_me as false it prompts all the time upon login, and when having remember_me as true it is always bypassed.

**Comment by larsschumachenko** [comment]
@Archehandoro As said, it depends on the settings on Azure AD side. At the end, aws-login is nothing else than a browser.
What happens when you login to the AWS GUI in your browser? Being it for the first time? What happens on subsequent logins to AWS? Do you always need to enter Password? MFA? Or is Microsoft accepting your recently renewed cookie?

**Comment by Archehandoro** [comment]
@larsschumachenko Settings on Azure AD are that once a day, actually every 8 hours, MFA is triggered. This is working as expected when connecting to the Web UI on AWS. However, as already mentioned, with aws-login if remember_me is false it prompts all the time and never if set to true.

**Comment by larsschumachenko** [comment]
Interesting. When you logged in through Web, did you tick the box when you've been asked for "Stay signed in?" at the end of the login flow, or didn't you tick it?

**Comment by Archehandoro** [comment]
> Interesting. When you logged in through Web, did you tick the box when you've been asked for "Stay signed in?" at the end of the login flow, or didn't you tick it?

I usually tick it.
