### ISSUE TITLE
Microsoft Authenticator phone sign in

### ISSUE THREAD

**Issue by FernandoMiguel** [aws-azure-login/aws-azure-login#128]
See https://docs.microsoft.com/en-us/azure/active-directory/user-help/user-help-auth-app-sign-in

I've enabled Phone Sign-in on Microsoft Authenticator 
It is a great password-less workflow.

But sadly breaks `aws-azure-login`
Is it possible to add a toggle to use this instead of the regular pass+mfa?

it would need to print out the `two-digit number` back to the console tho.

**Comment by kennethaasan** [comment]
That would be a nice feature. At this moment I don't have any capacity to implement it, but I'll happily review a PR.

**Comment by hermitmaster** [comment]
This already works with push notifications.
