### ISSUE TITLE
AWS CLI 2 Version with SSO Support

### ISSUE THREAD

**Issue by thomasgeens** [aws-azure-login/aws-azure-login#131]
Hi Guys, do you guys still see a need for this project or do you think the AWS CLI 2 has made this project redundant? 

As can be seen on this [blog about AWS SSO and Azure AD Enterprise Apps](https://thomas.geens.be/2020/05/31/combining-azure-ad-enterprise-apps-and-aws-sso-for-management-console-cli-and-programmatic-access-to-aws/), it seems the AWS CLI 2 Client now has full SSO Support.

**Comment by smudgeio** [comment]
I don't believe the AWS CLI 2 will currently work for IAM Identity Provider SAML Federation, only for the AWS Single Sign-On service, so this project would still be required.

This link shows the IAM Identity Provider SAML Federation configuration, as opposed to your AWS Single Sign-On link above.
https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/amazon-web-service-tutorial#configure-amazon-web-services-aws-sso.

**Comment by thejazzid** [comment]
Especially for China, as they don't have SSO, and only way is IAM identity provider with AzureAD for example.
