### ISSUE TITLE
aws-azure-login getting stuck at pick an account 

### ISSUE THREAD

**Issue by vamsee-v** [aws-azure-login/aws-azure-login#141]
when i try to login into aws-azure-login  getting below error: i can see in the error screen shot that its stuck at "pick an account".
system details

- Ubuntu 18.04 on Windows Subsystem for Linux 2

- docker image of aws-azure-login installed

steps to reproduce:
```
vamsee-v:/mnt/c/Users/Vamsee.vellala$ aws-azure-login
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png. If this problem persists, try running with --mode=gui or --mode=debug
```

![aws-azure-login error screen shot](https://user-images.githubusercontent.com/68371902/89770813-ea9dd180-db1c-11ea-8408-97f98d784d45.JPG)

**Comment by wilderbridge** [comment]
Stumbled to the same problem. In this case, delete `~/.aws/chromium` and try again.
