### ISSUE TITLE
[Session] Session Duration not being honored

### ISSUE THREAD

**Issue by josecolella** [aws-azure-login/aws-azure-login#142]
It seems as if the tool does not honor the session duration that is set during the input prompt and instead defaults to the deefault time that is located in the 

```sh
~/.aws/config
```

Version: aws-azure-login@2.2.2

Is there anything I can provide to assist with this issue?

**Comment by kennethaasan** [comment]
Hi @josecolella 

You're right. Made a fix in 2.2.4. Please close if that works for you.

**Comment by josecolella** [comment]
Thanks @kennethaasan

**Comment by e-power** [comment]
Hi I am using 2.2.4 and either I have it configured wrong or it doesn't work.

I have `azure_default_duration_hours=8 ` in `~/.aws/config` however `aws_expiration` in `~/.aws/credentials` only ever gets a duration of 1 hour
