### ISSUE TITLE
Error: Could not find browser revision 782078. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.

### ISSUE THREAD

**Issue by justinlazaro-iselect** [aws-azure-login/aws-azure-login#144]
![image](https://user-images.githubusercontent.com/54691710/91121982-afc69c80-e6cb-11ea-86e6-a26f0589b50c.png)

**Comment by kzoozer** [comment]
Seeing this issue over and over again. Is there a fix available ?

**Comment by luckb0x** [comment]
+1 -- started seeing error out of the blue on Windows machines.

**Comment by kennethaasan** [comment]
This seems to be a puppeteer issue: https://github.com/puppeteer/puppeteer/issues/6560

**Comment by RaviAtRACGP** [comment]
Actually you could set this no need code change

$env:PUPPETEER_EXECUTABLE_PATH='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'

this error went away. If you want happy to submit a PR

**Comment by salini-reddim** [comment]
> Actually you could set this no need code change
> 
> $env:PUPPETEER_EXECUTABLE_PATH='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
> 
> this error went away. If you want happy to submit a PR

where do you set this ? I have the same issue. 
Node 12.x
amplify cli 14.x
got this errror when my aws lambda tries to do chromium.puppeteer.launch to generate pdf from html

**Comment by emmaroberts-nbs** [comment]
I get the same issue even when setting the environment variable:
```bash
PUPPETEER_EXECUTABLE_PATH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"; aws-azure-login
```

The error is the same 
```
Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
    at PuppeteerNode.launch (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:125:31)
    at Object._performLoginAsync (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:458:49)
    at async Object.loginAsync (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:324:30)
```

Edit:
I removed the semi colon from my command and got further than the error.
Having to set the executable path every time using the command is non optimal and error prone

**Comment by walebant** [comment]
```
    const browserFetcher = puppeteer.createBrowserFetcher();

    const revisionInfo = await browserFetcher.download('809590.');

    const browser = await puppeteer.launch({ executablePath: revisionInfo.executablePath })
    
```
This fixed it for me

**Comment by ar-naseef** [comment]
I got the same error when I had puppeteer in `devDependencies`. Error vanished when I moved it into `dependencies`. Strange. I had it in `devDependencies` coz, I was using AWS Lambda layers and wanted to test locally.

**Comment by StillOnMyWay** [comment]
@ar-naseef This is exactly the same use case that I'm in. I'll test it as a direct dependency now instead. I had wanted to simulate how the SAM framework would work with local node_modules.
