### ISSUE TITLE
Change Browser

### ISSUE THREAD

**Issue by waldronj** [aws-azure-login/aws-azure-login#150]
In our environment we are using MFA conditional access policies. By default aws-azure-login is using chromium, is it possible to leverage chrome or another brower instead when using the --mode gui flag?

**Comment by kennethaasan** [comment]
@waldronj, you can try to use some of the env variables (_PUPPETEER_EXECUTABLE_PATH_ or _PUPPETEER_PRODUCT_) for puppeteer: https://github.com/puppeteer/puppeteer/blob/v5.3.0/docs/api.md#environment-variables

**Comment by waldronj** [comment]
Thank you! That did it, now to go work with the team managing conditional access.
