### ISSUE TITLE
--no-sandbox option returns `Unable to recognize page state! 

### ISSUE THREAD

**Issue by rchojn** [aws-azure-login/aws-azure-login#152]
Hello, when I am using --no-sandbox option I can not provide my email address: this is the first window that appears. After filling in form with my email and clicking "Next"  it's taking my to my organization sign in page (SSO). How to put this option to fill it or do it automatically to be able to pass username and password?

**Comment by tolonbai** [comment]
@gardnerdev Have  you resolved this issue ?

**Comment by tonis2** [comment]
Have you tried using Microsoft authenticator to login ?

**Comment by rchojn** [comment]
Yes, @tonis2 got point here
