### ISSUE TITLE
Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png.

### ISSUE THREAD

**Issue by Adblu** [aws-azure-login/aws-azure-login#158]
I have run out of space on my EC2 machine and I did not know. 
I tried to login with my aws-azure-login however I got an error:

```
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
[Error: ENOSPC: no space left on device, mkdtemp '/tmp/puppeteer_dev_chrome_profile-m8Ypzj'] {
  errno: -28,
  code: 'ENOSPC',
  syscall: 'mkdtemp',
  path: '/tmp/puppeteer_dev_chrome_profile-m8Ypzj'
}
```
I have released some more space and I have tried to log in again:

```
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png. If this problem persists, try running with --mode=gui or --mode=debug
```

Cound somebody help ?

**Comment by provMichaelHudson** [comment]
I am curious if you by chance configured your default profile to set 'Stay logged in' option to 'true' (this is the `azure_default_remember_me` setting in the config file)? I have found that I get this error when that is set to 'true' but everything works fine if it is set to 'false'.

Maybe set this to 'false' and see if that resolves the issue. I am hoping this helps anyone else that comes across this issue and also maybe helps the dev fix the issue.

**Comment by Adblu** [comment]
I have solved the problem by reinstalling node and everything related. But, yes, I had set "True" for azure_default_remember_me.

**Comment by JoyceShendre** [comment]
I was able to resolve this by first creating a profile with following command **aws-azure-login --configure --profile profile_name**, re-installing aws-cli and adding all the correct configuration details.
