### ISSUE TITLE
Snap release under a different name

### ISSUE THREAD

**Issue by franciscogouveia** [aws-azure-login/aws-azure-login#160]
In the documentation it mentions this snap: https://snapcraft.io/aws-azure-login
Unfortunately, this seems to not be valid anymore.

I did a quick search in the snap store and found this one: https://snapcraft.io/sportradar-aws-azure-login
Is it legit?

Thanks

**Comment by kennethaasan** [comment]
Hi @franciscogouveia

Thanks for the reminder! We've been waiting to get control over the name "aws-azure-login" for a long time. I made a fix for our snap publish job in https://github.com/sportradar/aws-azure-login/pull/168. Waiting for a manual review by snapcraft before it goes public as stable. 🤞  for a quick approval!

**Comment by franciscogouveia** [comment]
As far as I can see, this is fixed (https://snapcraft.io/aws-azure-login is there and last updated in late Jan 2021). Will close this issue.

Thanks!
