### ISSUE TITLE
install error - SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by Jlashton70** [aws-azure-login/aws-azure-login#161]
Hi

when running the command in Windows 10 desktop:
 npm install -g aws-azure-login

I get the following error:
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

regards
Luc

**Comment by decatur** [comment]
You are having an issue not specific to aws-azure-login.
Probably you are behind a firewall.
