### ISSUE TITLE
Unable to locate credentials. 

### ISSUE THREAD

**Issue by lu-chi** [aws-azure-login/aws-azure-login#190]
Hi,

the tools seems to be something I was looking for a very long time. However, when all is set as described on your website, azure login went well I cannot use aws cli at all receiving the messge as below when:
aws ec2 describe-instances --instance-ids <instance id> or other commands finsihing with:
"Unable to locate credentials. You can configure credentials by running "aws configure"."
Configuration is set correctly however it looks like it doesn't process the connection correctly.
Is there any type of env variables to be set or something else needs to be provided?
Base OSes: OSX, Linux - on both its' the same.

Thanks in advance!

**Comment by rharibal-conga** [comment]
I have the same issue.
What is the solution to this?
