### ISSUE TITLE
Option B does not work with zsh

### ISSUE THREAD

**Issue by strowk** [aws-azure-login/aws-azure-login#193]
I am using Ubuntu 20.04 and Zsh. Tried installing using `Option B: Install Only for Current User`  and I am getting this:
```
aws-azure-login
zsh: command not found: aws-azure-login
```

**Comment by davenicoll** [comment]
Zsh uses ~/.zprofile, rather than ~/.profile used by bash. If you're on a newer version of Ubuntu or a Mac, use this...
```
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH
source ~/.zprofile
echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.zprofile
source ~/.zprofile
```

**Comment by SJANAKIVENKATA** [comment]
i have faced same issue, how it solved for me is first install chromium (brew install --cask chromium)  after that run  (npm install -g aws-azure-login), then try  aws-azure-login it will work.

**Comment by engr-murad** [comment]
First I folow this way, it worked, after I uninstall and later did the same not working. (brew install --cask chromium) after that run (npm install -g aws-azure-login), not sure why.
