### ISSUE TITLE
" Dependabot cannot update css-what to a non-vulnerable version" because of aws-azure-login

### ISSUE THREAD

**Issue by l0b0** [aws-azure-login/aws-azure-login#195]
From a GitHub security alert in another repository:

> The latest possible version that can be installed is 4.0.0 because of the following conflicting dependencies:
> 
> aws-azure-login@3.3.0 requires css-what@^4.0.0 via a transitive dependency on cheerio-select-tmp@0.1.1
> aws-azure-login@3.3.0 requires css-what@^4.0.0 via a transitive dependency on css-select@3.1.2
> 
> The earliest fixed version is 5.0.1.

[cheerio-select](https://github.com/cheeriojs/cheerio-select/pull/45) and [css-select](https://github.com/fb55/css-select/issues/468) have updated their dependencies.

**Comment by l0b0** [comment]
Ping? This is considered high severity by `npm audit`.

**Comment by kennethaasan** [comment]
Released 3.4.0
