### ISSUE TITLE
login failures using chrome

### ISSUE THREAD

**Issue by thisis2394** [aws-azure-login/aws-azure-login#198]
Hi All,

I am getting below error in my corporate machine, since my organisation allow only apps that a verified by microsoft, sign in through chrome is failing given its a third party application. In my desktop browser i have installed windows 10 accounts extention and SSO for AWS console works as expected but i am not able to install windows 10 accounts extention to the chrome browser used by aws-azure-login package. Can someone suggest any workaround for this issue please.

![image](https://user-images.githubusercontent.com/60549807/127357484-32b5f63a-7b88-44ab-a7a8-c2887c239fe2.png)

**Comment by ErSandeepRajput** [comment]
I also faced the same problem.
The solution is use Microsoft Edge instead of Google Chrome by edit login.js (will find it under lib section) file follow.

![image](https://user-images.githubusercontent.com/39495357/138341583-9d33d9be-bca6-4610-8b8d-12d1eb5e1bdb.png)

**Comment by hermitmaster** [comment]
Puppeteer only officially supports the distribution of Chromium that is tied to their release. This isn't a configuration that we can offer support for.
