### ISSUE TITLE
Support MFA app push

### ISSUE THREAD

**Issue by aabrahamian** [aws-azure-login/aws-azure-login#2]
This tool is awesome but I would like to request the ability to support MFA with push instead of just a verification code.

In Security and Privacy (https://portal.office.com/account/#security), you can change the preferred option for how you can respond to the MFA request.
When I first installed your tool, I got errors because the default was set to
`notify me through app`
When I changed to 
`use verification code from app` 
it worked as expected.

Although there is a workaround here, it would be great to support the app push functionality (as it is less typing and faster). I was thinking a config would probably do the trick.

Let me know if you need any more details or other ways I can help out.

Thanks

**Comment by dtjohnson** [comment]
Thanks for finding this issue. I just published v0.3.0 that supports the various auth methods. I tried all of them out and they all seem to work now, including push notifications.

**Comment by aabrahamian** [comment]
That is some amazing turn around! 
Tested out my use case and it works beautifully.
Thanks so much!

**Comment by dtjohnson** [comment]
No prob.
