### ISSUE TITLE
issues w/ latest release on Windows

### ISSUE THREAD

**Issue by jyjohnson** [aws-azure-login/aws-azure-login#20]
I decided to update to the latest version (I was previously using the one based on PhantomJS)... And it is not working.

When I run the login command, the Chromium browser (GUI) opens... and after a few minutes the script times out with this error. I tried the --mode=cli option (didn't make a difference).

C:\Users\xxxx>aws-azure-login --profile dev
Logging in with profile 'dev'...
Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r526987
    at Timeout.onTimeout (C:\Users\xxxx\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Launcher.js:237:14)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

I'll try debugging later today/tonight... Posting here in case there is a quick fix.

Thanks.

**Comment by dtjohnson** [comment]
Nothing that I know of... Chrome is only supposed to be visible with the --mode=gui flag...

**Comment by tknarr** [comment]
I'm having the same problem. The --mode option appears to do nothing to change behavior.

**Comment by tylerjones4508** [comment]
@dtjohnson we are having the same issues.

**Comment by dtjohnson** [comment]
Seems to be a puppeteer issue: https://github.com/GoogleChrome/puppeteer/issues/1347

**Comment by tylerjones4508** [comment]
@dtjohnson Thanks

**Comment by jyjohnson** [comment]
I'm going to close this issue. I think I'm having issues b/c my company has some type of weird "Group Policy" that is preventing it from working (the prior version which used phantomjs did work).

Thanks.
