### ISSUE TITLE
30 sec timeout for login with --mode gui parameter

### ISSUE THREAD

**Issue by hiltuto** [aws-azure-login/aws-azure-login#23]
Navigation timeout exceeded 30 000 ms

Is it possible to modify the azure ad pop up login screen timeout, because 30 sec timeout is not so user friendly?  60 sec timeout would be nice

**Comment by dtjohnson** [comment]
I'm sorry, which timeout are you talking about?

**Comment by dtjohnson** [comment]
Oh, I'm guessing this is a dup of https://github.com/dtjohnson/aws-azure-login/issues/20

**Comment by dtjohnson** [comment]
Should be fixed in v1.3.0.
