### ISSUE TITLE
Azure login page format changed

### ISSUE THREAD

**Issue by yuxiangl** [aws-azure-login/aws-azure-login#24]
The format of the Azure login page where it's prompting for the user's password has changed. As a result, users cannot submit their passwords to the Azure login page.

The login page changes are:

- name of the password input field changed from 'passwd' to 'Password'

- submit button changed from an input element to a span element

The error message after typing in the password is:

>   aws-azure-login Focusing on username input +726ms
>   aws-azure-login Clearing input +4ms
>   aws-azure-login Typing username +176ms
>   aws-azure-login Submitting form +50ms
>   aws-azure-login Request: https://login.microsoftonline.com/common/GetCredentialType +18ms
>   aws-azure-login Waiting for submission to finish +507ms
>   aws-azure-login Finished state: username input +1s
>   aws-azure-login State not recognized! +8ms
>   aws-azure-login State not recognized! +2ms
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
>   aws-azure-login State not recognized! +1s
> Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png. If this problem persists, try running with --mode=gui or --mode=debug

**Comment by dtjohnson** [comment]
That's rather odd. I'm not seeing a change when I try logging in...

**Comment by yuxiangl** [comment]
I guess this change is isolated to my organization's Azure login page...

**Comment by dtjohnson** [comment]
Perhaps it is something MS is rolling out slowly. If you can make the selectors support both format's I'll accept the PR.

**Comment by nhmaha** [comment]
+1 getting same 

Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png. If this problem persists, try running with --mode=gui or --mode=debug

**Comment by yuxiangl** [comment]
I updated the selectors to support both formats

**Comment by dtjohnson** [comment]
Thanks! PR merged in v1.3.0.
