### ISSUE TITLE
TypeError when trying to use aws-azure-login

### ISSUE THREAD

**Issue by rumbogs** [aws-azure-login/aws-azure-login#26]
Using aws-azure-login@1.3.0.
Try to login using `aws-azure-login`, input your username and password, then hit enter, the following is displayed:
```
info: TypeError: null is not an object (evaluating 'document.getElementById("uxOptOutLink").click')
info:   undefined:2 in anonymous
info:   :4
```
And the process is stalling.

`aws-azure-login --mode gui` works as expected.

**Comment by dtjohnson** [comment]
Likely some weird puppeteer issue. Please try with the latest version.

**Comment by kennethaasan** [comment]
Old issue. Please re-open if this is still a problem for you with the latest version.
