### ISSUE TITLE
Add support for the increased session duration

### ISSUE THREAD

**Issue by myron-semack-old** [aws-azure-login/aws-azure-login#28]
Amazon now permits temporary API credentials up to 12 hours:
https://aws.amazon.com/blogs/security/enable-federated-api-access-to-your-aws-resources-for-up-to-12-hours-using-iam-roles/

It would be great if the call to sts.assumeRoleWithSAML() should be updated to support passing in a longer timeout parameter.  Note that AWS admins can specify the maximum duration when they setup the IAM role, so this should probably be a command line parameter or something you can set in the profile.

**Comment by dtjohnson** [comment]
This is amazing news! Will definitely get this added.

**Comment by dtjohnson** [comment]
Done in v1.4.0
