### ISSUE TITLE
Chromium opens but does not do anything from there.

### ISSUE THREAD

**Issue by mmaxin** [aws-azure-login/aws-azure-login#31]
Hi, I seem to be having an issue where chromium loads but does not navigate anywhere from there. 

It displays an error message about not finding chrome,
The log: https://gist.github.com/mmaxin/2272fc6838d10a5d34f6251a59578415

**Comment by mike-hosseini** [comment]
This does not appear to be happening, if you run into again, please open a new issue with steps to reproduce this specific problem.
