### ISSUE TITLE
Chromium not loading the page

### ISSUE THREAD

**Issue by gitven** [aws-azure-login/aws-azure-login#35]
Hello dtjohnson,
Get this error upon entering the user name for logging in, screen shot is just a blank page

Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png. If this problem persists, try running with --mode=gui or --mode=debug

 node -v
v8.11.3

npm -v
6.1.0

ldd chrome | grep not is clean

**Comment by gitven** [comment]
![aws-azure-login-unrecognized-state](https://user-images.githubusercontent.com/15182761/41734426-7ce964a2-754c-11e8-8cd8-0170931d1324.png)

**Comment by pagemedias** [comment]
Had same issue and seemed to be chrome security issue with certificate. Found error by —mode=gui. 

Downgraded chrome and now seem to be getting this issue where just hangs https://github.com/dtjohnson/aws-azure-login/issues/31

**Comment by rhoml** [comment]
This is still kind of happening today under a weird set of conditions.

We are currently using Azure AD and we want to migrate from Azure MFA into DUO for MFA, when we pass the authentication and wait for Duo's iframe looks like the Chromium window just freezes, it doesn't finish loading or it doesn't load at all.

I don't think this is an issue with aws-azure-login but the Chromium dependency may have broken something.

Unfortunately, debug logs doesn't give me anything and the inspector just stops at one of duosecurity api calls.

**Comment by kennethaasan** [comment]
Old issue. Please re-open if this is still a problem for you with the latest version.
