### ISSUE TITLE
Needed to add args.push('--enable-features=NetworkService'); to overcome redirect to external vendor in auth workflow

### ISSUE THREAD

**Issue by miguelfeitosa** [aws-azure-login/aws-azure-login#36]
Hello,

I am happy to make a pull request but could not commit to repo.
This is very useful code and many of us here use it to login...

We had  the issue described https://github.com/GoogleChrome/puppeteer/issues/1664 for a scenario where microsoft.com was sending a redirect to a vendor page to collect credentials.

We debugged with:
DEBUG=aws-azure-login aws-azure-login --mode gui

The app freezes right after specifying the name in the first page.
This  I suppose is a common scenario.
I am happy to create a pull request, the one open question is should this be a runtime flag or just always set, possibly this should always be set or only be set based on other user flags. Regardless, I am happy to create the pull request but was unable to as github denied me access to the repo so I decided to send as an issue then depending on how to resolve I will then fork the repo as suggested but seems cumbersome for a few lines of change.

 git diff freeze_on_vendor_auth master
diff --git a/lib/login.js b/lib/login.js
index 376b3e8..0dda066 100644
--- a/lib/login.js
+++ b/lib/login.js
@@ -332,7 +332,6 @@ module.exports = {
         try {
             const args = headless ? [] : [`--app=${url}`, `--window-size=${WIDTH},${HEIGHT}`];
             if (disableSandbox) args.push('--no-sandbox');
+            args.push('--enable-features=NetworkService');
 
             browser = await puppeteer.launch({
                 headless,

**Comment by blayzestefaniak** [comment]
+1, Thank you Miguel

**Comment by dtjohnson** [comment]
If it works, I'm happy to take the PR. The only concern is that that issue says NetworkService isn't ready yet.

**Comment by miguelfeitosa** [comment]
Hey Dave!
Great work on the tool...we have been using it....
I made two changes, the NetworkService one and one more to allow the use of
self signed certificates.
I think they would be nice optional flags.
I tried creating a pull request to send you the work but when I go to git
clone the repo, to then create a branch.
I don't use github a lot so this is possibly me just not understanding how
to create a branch for your review.
It says something to the effect, you cannot clone this repo, you may have
to fork instead...
Is there any flag or option you need to set to allow anyone from the public
to clone your repo?
Tomorrow morning I will try to clone your repo again and get back to you on
the exact error message I see.
It may be me fubaring...
Thanks
Miguel

**Comment by miguelfeitosa** [comment]
not it cloned, go figure...I will work on getting something up for us to
discuss a bit...

**Comment by miguelfeitosa** [comment]
Hi Dave,
I created a branch with both option changes we made to the tool.
I wanted to send to you for you to take a look.
I can't run git push to the repo though.
Would you rather I email you a patch for you to take a look ?
Note; Our changes help support some common corporate scenarios.

Thanks  a bunch!
Below the issue I have when I try to push.
I can now clone.

[dso@localhost aws-azure-login]$ git remote show origin
* remote origin
  Fetch URL: https://github.com/dtjohnson/aws-azure-login.git
  Push  URL: https://github.com/dtjohnson/aws-azure-login.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
[dso@localhost aws-azure-login]$ git status
On branch add_option_disable_ssl_checking
nothing to commit, working tree clean
[dso@localhost aws-azure-login]$ git push origin add_option_disable_ssl_checking 
Username for 'https://github.com': miguelfeitosa
Password for 'https://miguelfeitosa@github.com': 
remote: Permission to dtjohnson/aws-azure-login.git denied to miguelfeitosa.
fatal: unable to access 'https://github.com/dtjohnson/aws-azure-login.git/': The requested URL returned error: 403
[dso@localhost aws-azure-login]$

**Comment by rhoml** [comment]
Oh this PR might solve some problems I am having with Azure + Duo MFA.

**Comment by miguelfeitosa** [comment]
cool!...let me know...will be happy if so!

**Comment by kennethaasan** [comment]
Hi @miguelfeitosa,
You have to fork this repo to your own user, then submit a PR to this repo: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Since this is an old issue I'll close it soon unless you don't send a PR.

**Comment by miguelfeitosa** [comment]
Hi Kenneth,
Cool, thanks for reaching out.
I believe this got solved and merged a while ago.
Please go ahead and close...
Thanks for the tool, we use it daily!!!

Miguel
