### ISSUE TITLE
Role & Principal ARNs may be in either order in role claim

### ISSUE THREAD

**Issue by mr-olson** [aws-azure-login/aws-azure-login#4]
AWS doesn't seem to mind which order Role & Principal ARN are provided in claims. The string ":role/" seemed a relatively safe way to determine which is which though, so here's how I solved it in login.js.

Thanks for publishing your work, it's a huge help!

                const roleAndPrincipal = saml(this).text();
                const parts = roleAndPrincipal.split(",");
                // Role / Principal claims may be in either order
                const roleIdx = parts[0].indexOf(":role/") != -1 ? 0 : 1;
                const principalIdx = roleIdx == 0 ? 1 : 0;
                const roleArn = parts[roleIdx].trim();
                const principalArn = parts[principalIdx].trim();
                return { roleArn, principalArn };

**Comment by dtjohnson** [comment]
Good catch. Want to submit a PR?

**Comment by dtjohnson** [comment]
Thanks for the PR. I just published v0.4.1.
