### ISSUE TITLE
Easier way to get AZURE_TENANT_ID:

### ISSUE THREAD

**Issue by inrix-travis-barnard** [aws-azure-login/aws-azure-login#42]
There is an easier way to retrieve your Azure Tenant ID

Login to the Azure portal and select the Amazon Web Services Enterprise Application.
Under Manage: Select Single Sign-On
Scroll down to 4. SAML Signing Certificate
You will see the full App Federation Metadata URL with a convenient copy option right next to it.
![screen shot 2018-07-25 at 2 38 45 pm](https://user-images.githubusercontent.com/15914762/43229168-b1ad7f16-9018-11e8-8e04-a022aa8bf1a6.png)

**Comment by kiernan** [comment]
Or just using the domain name of the tenant seems to work. e.g. `contoso.com`, `contoso.onmicrosoft.com`

**Comment by mike-hosseini** [comment]
Thanks for posting this tip. This does not appear to be an issue, if you want to improve the repository with this information, feel free to send a pull request.
