### ISSUE TITLE
Support multiple MFA providers (Duo)

### ISSUE THREAD

**Issue by rhoml** [aws-azure-login/aws-azure-login#51]
It would be nice if this tool supported DUO as well as Microsoft Authenticator.

**Comment by scumola** [comment]
I believe that I'm getting this issue too.

My login.microsoftoffice.com url doesn't contain a SAMLRequest parameter.  My Azure AD is configured to use the MS Office Authenticator app.  My login url looks like:  

https://login.microsoftonline.com/GUID/oauth2/authorize?client_id=0000000c-0000-0000-c000-000000000000&redirect_uri=https%3A%2F%2Faccount.activedirectory.windowsazure.com%2F&response_mode=form_post&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3Dxxxxxxxx&nonce=xxxxxxxx&nux=1

**Comment by rhoml** [comment]
This actually works out of the box but you need to configure Duo to send a push notification by default.
