### ISSUE TITLE
Support Passwordless Auth

### ISSUE THREAD

**Issue by davepattie** [aws-azure-login/aws-azure-login#52]
Please can you add support for passwordless auth.  When you enable phone signin in Microsoft Authenticator you are prompted with a number instead of having to enter your password.  The MFA approval prompt on your phone then shows three numbers and you must select the correct one. 

![passwordless auth](https://user-images.githubusercontent.com/11752779/47284924-fa16f800-d5e0-11e8-81d3-31af10129695.JPG)

Please can you therefore update to prompt the number on the screen or if the use password hyperlink is present virtually select that and pass the username and password through to that screen instead.

Thanks

**Comment by davepattie** [comment]
Passwordless auth is pretty much the standard these days, it would be great if you can find time to address this.  The workaround is to run aws-azure-login twice, the first time it will ask for username twice, the 2nd attempt will work but that's getting quite tedious for users, cheers

**Comment by kennethaasan** [comment]
Hey, 

Sorry, I don't have any capacity to add this at this moment. A PR that adds support for Passwordless Auth would be lovely!
