### ISSUE TITLE
Windows 10 --mode gui not opening window

### ISSUE THREAD

**Issue by sethbacon** [aws-azure-login/aws-azure-login#54]
using latest aws-azure-login --mode gui hangs at "please complete the login in the opened window"
Windows 10 Build 1803

**Comment by RaviAtRACGP** [comment]
Is this the same issue? I'm running the code locally. Command line doesn't accept any input to make it run

![image](https://user-images.githubusercontent.com/23691150/99198758-da1d8700-27ee-11eb-972f-fbc3f87b8ff1.png)
