### ISSUE TITLE
Stalls after entering password in CLI

### ISSUE THREAD

**Issue by boozrun** [aws-azure-login/aws-azure-login#58]
Hi,

The install has been completed and configured. When running aws-azure-login, prompted to enter username and password. Once the password is entered, it stalls and nothing happens. 

Any advice or help with this issue would be appreciated. 

Node version 10.14.1
NPM version 6.4.1
aws-azure-login version 1.7.0

Thanks,

**Comment by wdtmatt** [comment]
Seeing the same thing here.   Works fine with GUI but cli hangs after password input.

**Comment by asnell** [comment]
Same, running in console mode.

Node 10.16.0
NPM 6.9.0
aws-azure-login 1.7.0
CentOS 7.6

Enabling debug logging doesn't reveal anything - it seems to just do nothing at all after entering the password:

```  aws-azure-login Finished state: username input +18ms
  aws-azure-login Found state: password input +7ms
  aws-azure-login Prompting user for password +5ms
? Password: [input is hidden]
```

**Comment by hermitmaster** [comment]
Stale, closing.
