### ISSUE TITLE
Tool is broken on macOS 10.14.5 (Docker only)

### ISSUE THREAD

**Issue by mike-watkins-versent** [aws-azure-login/aws-azure-login#70]
I've been using this tool for the past 6 or so weeks with the occasional glitch but generally it works, in fact I was using it up to yesterday afternoon and it was working perfectly, then a couple of hours later it just no longer works.

I'm using the latest version and running the Docker container version to avoid any machine dependencies causing an issue.

`docker run --rm -it -v ~/.aws:/root/.aws dtjohnson/aws-azure-login --configure`
(works as expected)
- prompts for the required args, accepts what I enter
- adds an entry in `~/.aws/config` as the `[default]` profile

`docker run --rm -it -v ~/.aws:/root/.aws dtjohnson/aws-azure-login`
(broken)
- prompts for username, accepts what I enter
- prompts for password
- hangs indefinitely

`DEBUG=aws-azure-login aws-azure-login`
(broken)
- prompts for username, accepts what I enter
- prompts for password
- hangs indefinitely
- no log files or screenshot files are found anywhere (checked in source repo folder, home dir, desktop, ~/.aws)

`docker run --rm -it -v ~/.aws:/root/.aws dtjohnson/aws-azure-login --mode gui`
(broken)
- outputs the following error
```
Logging in with profile 'default'...
Error: Failed to launch chrome!

(chrome:16): Gtk-WARNING **: cannot open display:


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:333:14)
    at ChildProcess.helper.addEventListener (/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:323:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

Details of my environment;
- Macbook Pro running macOS 10.14.5 (latest)
- Docker Desktop Community 2.0.0.3 stable (Engine: 18.09.2)
- Node 10.6.0 & NPM 6.1.0
- Not using a proxy
- MFA is enabled in Azure IDP

Things I have tried so far;
- Restart OS
- Updated to latest OS
- Deleted the Docker container, image(s) and prune system/network/volume/etc
- Updated Docker daemon to latest version
- Verified my credentials work by using the same SAML flow via the web console (login successful)
- Verified other Mac users in my org running older versions of macOS can run the tool fine

**Comment by mike-watkins-versent** [comment]
Have also trolled the internet for issues with macos/chrome/puppeteer, nothing useful so far. 

Also read over that troubleshooting link in the error (https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) which mentions nothing about Mac but none of the Linux tips seem to apply either.

**Comment by mike-watkins-versent** [comment]
Also just tried upgrading to latest Node (now 12.3.1) and NPM (now 6.9.0) - still same results as above. Note that running as Docker container and running native have the same result.

**Comment by mike-watkins-versent** [comment]
Okay, finally got it working natively via Node at least.
- Uninstalled `aws-azure-login` entirely
- Cleared aws creds/config files
- Deleted every docker container/image/volume + prune all
- Unistalled Node (brew)
- Restart machine
- Install Node (brew)
- Install `aws-azure-login`

Now the tool works as expected. 

Still entirely broken if I use the Docker container, so obviously that's where things are broken. Have updated the title of the ticket to reflect this.

**Comment by mike-hosseini** [comment]
That seems to be an issue with Puppeteer not being able to start headless Chrome in a Docker container. It is not a bug with the tool itself. You can try building the Dockerfile yourself and find the issue, I will try to look into it time-allowing.

**Comment by mike-hosseini** [comment]
I ran a few tests, I am not able to replicate this issue and aws-azure-login works fine in a Docker container. The image may be outdated on Dockerhub and I have no access to it, you can build the Docker file from the repository and use it that way. If you run into any issues with that approach, open a new issue.
