### ISSUE TITLE
Only works for 1 hour

### ISSUE THREAD

**Issue by lorenh** [aws-azure-login/aws-azure-login#77]
While logging in, whenever I put in anything greater than 1 hour I receive this error:

Session Duration Hours (up to 12): 4

Error [ValidationError]: The requested DurationSeconds exceeds the MaxSessionDuration set for this role....

Where is MaxSessionDuration configured to allow longer times?

Thanks!

**Comment by mol-ie** [comment]
![image](https://user-images.githubusercontent.com/4391456/63688111-c1236180-c849-11e9-8af4-ec19377adfe3.png)

Set the Maximum CLI\API session duration to more than 1 hour, in the IAM Console for the Role you are trying to assume, this error us coming from the AWS SDK, not Azure. See the screenshot attached. 

If it works you can verify the credential the session expiry looking for the following variable in the credentials file.

aws_session_expiration=2019-08-26T23:37:42.000Z

**Comment by AMMullan** [comment]
Yeah, @michael-oleary answer is spot on - I can confirm that if I try using a Session Duration longer than what is set in the AWS IAM Role I get the same message but that is what I'd expect. 

Might be a nicer user experience if the exception was caught and printed nicer but not a biggie IMO.

**Comment by varun-viva** [comment]
@kennethaasan @michael-oleary 
We have updated the session timeout to 12 hours in AWS for the roles, but still the token expires in 15 min

**Comment by larsschumachenko** [comment]
@varun-viva Just to double check: Did you also update your client configuration and set it to 12 hours? Only adjusting the allowed maximum on AWS side is not enough, you need to reconfigure the client and then issue a new token with the new validity timespan.

On the other side: You mentioned it expires after 15 minutes. That sounds like you probably do something else, eg use the credentials gathered by aws-azure-login and use them with sts to create another session. Then the solution is different and probably has nothing to do with aws-azure-login.

**Comment by varun-viva** [comment]
@larsschumachenko Yes we re-ran the client configuration and set the timeout as 12 hours. But the newly generated token is working only for 12-15min it seems. We are using Azure AD for authentication. Does it have anything to do with that ? When the token is generated the token expiry shown is within 15 min.

**Comment by varun-viva** [comment]
@larsschumachenko issue was fixed for me after setting token expiry in Azure AD

**Comment by dc-pm** [comment]
@varun-viva can you specify where in Azure AD you set the token expiry? We have the same 15min problem.

**Comment by fmoralvi** [comment]
@varun-viva and @dc-pm 
I changed the SessionDuration Attribute in the AAD. In the AWS console, I see the SessionDuration Attribute modified in the SAMLResponse:
        Attribute Name="https://aws.amazon.com/SAML/Attributes/SessionDuration">
                AttributeValue>3600</AttributeValue>
            /Attribute
Instead, In the sportradar, when the token is generated, the token expery shows 15 min.
Any ideas about it?
