### ISSUE TITLE
Error running aws-azure-login --configure

### ISSUE THREAD

**Issue by cpollard0** [aws-azure-login/aws-azure-login#8]
Install works great, when I run aws-azure-login --configure i get an error: 

aws-azure-login\lib\configureProfileAsync.js:6

module.exports = async profileName => {

syntaxError: Unexpected Identifier

Any suggestions?

**Comment by dtjohnson** [comment]
What version of Node.js do you have? Only v6+ is supported.

**Comment by cpollard0** [comment]
v6.11.3

**Comment by dtjohnson** [comment]
Oh, right. I forgot that I updated to use async/await which is Node 7+. You can either upgrade Node (current version is 8.4) or downgrade aws-azure-login to v0.5.0.

**Comment by cpollard0** [comment]
That got me further; thanks!
