### ISSUE TITLE
Feature Request: Export AWS_ variables to environment

### ISSUE THREAD

**Issue by felipe1982** [aws-azure-login/aws-azure-login#90]
Ansible uses boto v2 and so has some trouble with getting credentials from .aws/credentials compared with boto3.

A work around is for Ansible to read environment variables `AWS_SESSION_TOKEN` `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

To provide this capability, some tools (saml2aws) provide a way to export the `AWS_*` environment variables to the environment, so they can be picked up by Ansible.

Request:
Could you please provide a way for the environment variables to be exported to the environment, or printed to screen to be used by `eval` ?

**Comment by kennethaasan** [comment]
@felipe1982 this sounds like something a little bit out of the scope of this tool. But we could try to add an option to print something that could be used by `eval`. Can you send a PR?

**Comment by felipe1982** [comment]
I would love to submit a PR but I'm not a developer or programmer. So sorry.

**Comment by felipe1982** [comment]
I am using [/trek10inc/awsume](/trek10inc/awsume) and it is serving this purpose well.
