### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by kennethaasan** [aws-azure-login/aws-azure-login#95]
I just took over as a maintainer of this tool, and I would like to set a few goals for a 2.0 version of this tool. It should not be any breaking changes or new features for the tool itself, but code improvements. For example, there are no tests in the codebase today.

1. ✔️Convert the code to `TypeScript` for type safety.
2. ✔️Use `prettier` for code formatting
2. Use the `jest` testing framework for testing. Add tests for the core features and expand.
3. Publish the tool to `snap`.

Feel free to discuss my suggestions and make new suggestions.

**Comment by wojtek-oledzki** [comment]
suggested features:
* add --forceRefresh to normal login - https://github.com/sportradar/aws-azure-login/pull/97
  ```BASH
  $ aws-auzure-login --profile lorem-ipsum
  Profile lorem-ipsum not yet due for refresh.
  ```
* add option to output generated creds - In case I don't want to update my ~/.aws/credentials file, and maybe export it to your current shell.
  ```BASH
  $ aws-azure-login --profile lorem-ipsum --stdOutput
  export AWS_ACCESS_KEY_ID=ASI...LFV AWS_SECRET_ACCESS_KEY=rJv...pc6 AWS_SESSION_TOKEN=FQo...u0F AWS_SECURITY_TOKEN=FQo...5u0F
  ```

**Comment by kennethaasan** [comment]
@wojtek-oledzki,

I'll take a look at those during the holidays. Finally have a bit more time to maintain this project. I just released _TypeScript_ and _prettier_ today.

**Comment by muthusk** [comment]
Suggesting usage of keyring [114](https://github.com/sportradar/aws-azure-login/issues/114) to storing and retrieving password

**Comment by CodySchluenz** [comment]
I suggest allowing parsing of SAML assertions from a file #113
