### ISSUE TITLE
Configuration non-interactive

### ISSUE THREAD

**Issue by cleverton-heusner** [aws-azure-login/aws-azure-login#98]
I'm in Ubuntu and would like a non-interactive way of configuring the login. It's for a jenkins pipeline.

I can authenticate myself without prompt through environment variables like this: 
`aws-azure-login --no-prompt`

However, in the configuration, the `--no-prompt` option doesn't works:
`aws-azure-login --configure --no-prompt`

Can anyone help with this, please?

**Comment by olemarkus** [comment]
`--configure` is explicitly intended for setting the config through CLI. If you want to automate this, it is better to just directly add the variables to `.aws/config`.
